# This file is generated by scripts/generate-formula.ts. Do not edit by hand.
class Ghqv < Formula
  desc "Virtual monorepo workspace manager for ghq-managed repositories"
  homepage "https://github.com/Yicru/ghqv"
  license "MIT"
  version "0.3.1"

  depends_on "ghq"
  depends_on "fzf"

  on_macos do
    on_arm do
      url "https://github.com/Yicru/ghqv/releases/download/v0.3.1/ghqv_0.3.1_darwin-arm64.tar.gz"
      sha256 "a6acac31bb5cfbfd4c700f382e6f594c93f3c55edd526e41b34b70ec1d760af0"
    end
    on_intel do
      url "https://github.com/Yicru/ghqv/releases/download/v0.3.1/ghqv_0.3.1_darwin-x64.tar.gz"
      sha256 "f652d30ad8ffa9cbe8d15f86fce7e123e3d64d9ae0d771c00c208da97fb8265a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Yicru/ghqv/releases/download/v0.3.1/ghqv_0.3.1_linux-arm64.tar.gz"
      sha256 "a1b2a69c8cc1ceb0a2e3a230df0f40db66558b24059119a550600fbfe22673c0"
    end
    on_intel do
      url "https://github.com/Yicru/ghqv/releases/download/v0.3.1/ghqv_0.3.1_linux-x64.tar.gz"
      sha256 "95c38aefd62a0db8d371a22f0d6484c5330e962e477a5cd1c1c57cc7dbb9dfbd"
    end
  end

  def install
    bin.install "ghqv"
  end

  test do
    assert_match "ghqv", shell_output("#{bin}/ghqv --version")
  end
end
