# This file is generated by scripts/generate-formula.ts. Do not edit by hand.
class Ghqv < Formula
  desc "Virtual monorepo workspace manager for ghq-managed repositories"
  homepage "https://github.com/Yicru/ghqv"
  license "MIT"
  version "0.3.0"

  depends_on "ghq"
  depends_on "fzf"

  on_macos do
    on_arm do
      url "https://github.com/Yicru/ghqv/releases/download/v0.3.0/ghqv_0.3.0_darwin-arm64.tar.gz"
      sha256 "b7f357b52061dfec75236c127dbeb9267b5530dbb372f7b6337ce45621a81da4"
    end
    on_intel do
      url "https://github.com/Yicru/ghqv/releases/download/v0.3.0/ghqv_0.3.0_darwin-x64.tar.gz"
      sha256 "29909d52487e53fe4d69b2e0c824cfba427286052a2b57d9cee44aa20aaf7eed"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Yicru/ghqv/releases/download/v0.3.0/ghqv_0.3.0_linux-arm64.tar.gz"
      sha256 "7cfda3b9beec44d4609fdb80ad54f1f01a1dfa12c20e2f39625c086d44440d8e"
    end
    on_intel do
      url "https://github.com/Yicru/ghqv/releases/download/v0.3.0/ghqv_0.3.0_linux-x64.tar.gz"
      sha256 "21b597cdc53a67f280aa980fcca6febdeeb9d804eeeb640b259677878ecb3461"
    end
  end

  def install
    bin.install "ghqv"
  end

  test do
    assert_match "ghqv", shell_output("#{bin}/ghqv --version")
  end
end
