# This file is generated by scripts/generate-formula.ts. Do not edit by hand.
class Ghqv < Formula
  desc "Virtual monorepo workspace manager for ghq-managed repositories"
  homepage "https://github.com/Yicru/ghqv"
  license "MIT"
  version "0.2.0"

  depends_on "ghq"

  on_macos do
    on_arm do
      url "https://github.com/Yicru/ghqv/releases/download/v0.2.0/ghqv_0.2.0_darwin-arm64.tar.gz"
      sha256 "dda766d77646afda42d703106649294b96878cf9678b6984243a5aeaf57b5ac9"
    end
    on_intel do
      url "https://github.com/Yicru/ghqv/releases/download/v0.2.0/ghqv_0.2.0_darwin-x64.tar.gz"
      sha256 "26926aa31ba34b912d6513b4bc98d01c4be6f1721bb68e835e387c8969f69e92"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Yicru/ghqv/releases/download/v0.2.0/ghqv_0.2.0_linux-arm64.tar.gz"
      sha256 "40bb9713d774185e4e54e3c4dd939a3afa01daa3cd3d136b0d311fd45e3e8236"
    end
    on_intel do
      url "https://github.com/Yicru/ghqv/releases/download/v0.2.0/ghqv_0.2.0_linux-x64.tar.gz"
      sha256 "f1efe6c4eb3a683caddd97fc548f6027b04437fd00132bf80bb3030a7e6254aa"
    end
  end

  def install
    bin.install "ghqv"
  end

  test do
    assert_match "ghqv", shell_output("#{bin}/ghqv --version")
  end
end
